/* ===========================================================================
   keyData.ts: SEED DATA
   ---------------------------------------------------------------------------
   The database is seeded from the arrays below on first run. After that the
   whole site reads from Postgres, so admin edits are live. HTML is allowed in
   text fields (<b> to bold key terms, <i> for italics).
   =========================================================================== */
import type {
  Organism,
  KeyNode,
  SiteMetaData,
} from "./types";

/* --- 20 organisms (sort defines gallery order within each kingdom) --- */
export const seedOrganisms: Organism[] = [
  // Plantae
  { id: "sphagnum", common: "Sphagnum Moss", binomial: "Sphagnum capillifolium", kingdom: "plantae", grp: "Kingdom Plantae · Bryophyta (mosses)", image: "/organisms/sphagnum.png", alt: "Photograph of a dense carpet of Sphagnum Moss (Sphagnum capillifolium)", caption: "Gardening Know How. (n.d.). Sphagnum moss [Photograph]. https://www.gardeningknowhow.com/garden-how-to/soil-fertilizers/sphagnum-moss-vs-sphagnum-peat-moss.htm", sort: 0,
    diagnostic: "A <b>non-vascular</b> plant (bryophyte) with no <b>xylem</b> or <b>phloem</b>; it absorbs water directly and reproduces by <b>spores</b>, forming the <b>peat</b> of Algonquin's bogs.",
    traits: ["<b>Non-vascular</b> (no <b>xylem</b>/<b>phloem</b>)", "<b>Photosynthetic</b>, multicellular", "Absorbs water directly", "Reproduces by <b>spores</b>; builds <b>peat</b>"] },
  { id: "matteuccia", common: "Ostrich Fern", binomial: "Matteuccia struthiopteris", kingdom: "plantae", grp: "Kingdom Plantae · Polypodiopsida (ferns)", image: "/organisms/matteuccia.png", alt: "Photograph of Ostrich Fern (Matteuccia struthiopteris)", caption: "Dutch Growers. (n.d.). Ostrich fern [Photograph]. https://plants.dutchgrowers.net/11040004/Plant/1781/Ostrich_Fern/", sort: 1,
    diagnostic: "A <b>seedless vascular</b> plant (<b>pteridophyte</b>) with true <b>xylem</b> and <b>phloem</b> and large <b>fronds</b>; it reproduces by <b>spores</b> in <b>sori</b>, not seeds.",
    traits: ["<b>Vascular</b> but <b>seedless</b> (<b>pteridophyte</b>)", "Large feathery <b>fronds</b>", "<b>Spores</b> in <b>sori</b> under fronds", "True <b>xylem</b> and <b>phloem</b>"] },
  { id: "pinus", common: "Eastern White Pine", binomial: "Pinus strobus", kingdom: "plantae", grp: "Kingdom Plantae · Pinophyta (conifers)", image: "/organisms/pinus.png", alt: "Photograph of Eastern White Pine (Pinus strobus)", caption: "Sylvan Gardens Landscape. (n.d.). Eastern white pine [Photograph]. https://sylvangardenslandscape.com/plant-profile/eastern-white-pine-plant-profile/", sort: 2,
    diagnostic: "A <b>gymnosperm</b>: a <b>vascular</b> seed plant bearing \"naked\" <b>seeds</b> on woody <b>cones</b>, with needle leaves. Ontario's provincial tree.",
    traits: ["<b>Vascular</b> <b>gymnosperm</b>", "Naked <b>seeds</b> on woody <b>cones</b>", "Needle leaves in bundles of five", "<b>Wind-pollinated</b>; evergreen"] },
  { id: "trillium", common: "White Trillium", binomial: "Trillium grandiflorum", kingdom: "plantae", grp: "Kingdom Plantae · Angiosperms · Monocot (Liliopsida)", image: "/organisms/trillium.png", alt: "Photograph of White Trillium (Trillium grandiflorum)", caption: "Gardenia. (n.d.). Trillium grandiflorum (white trillium) [Photograph]. https://www.gardenia.net/plant/trillium-grandiflorum-white-trillium", sort: 3,
    diagnostic: "A <b>flowering plant</b> (<b>angiosperm</b>) whose <b>monocot</b> traits show in <b>parallel</b> leaf veins and flower parts in threes. Ontario's floral emblem.",
    traits: ["<b>Angiosperm</b> (seeds in an ovary)", "<b>Monocot</b>: <b>parallel</b> venation", "Flower parts in threes", "Spring woodland wildflower"] },
  { id: "acer", common: "Sugar Maple", binomial: "Acer saccharum", kingdom: "plantae", grp: "Kingdom Plantae · Angiosperms · Dicot (Magnoliopsida)", image: "/organisms/acer.png", alt: "Photograph of Sugar Maple (Acer saccharum) in autumn colour", caption: "Dutch Growers. (n.d.). Sugar maple [Photograph]. https://plants.dutchgrowers.net/11040004/Plant/22/Sugar_Maple/", sort: 4,
    diagnostic: "A <b>flowering plant</b> (<b>angiosperm</b>) with <b>dicot</b> traits: broad leaves with <b>net-like veins</b> and flower parts in fours/fives. Source of maple syrup.",
    traits: ["<b>Angiosperm</b> (seeds in a fruit)", "<b>Dicot</b>: <b>net-like</b> veins", "Broad lobed leaves; winged <b>samara</b>", "Deciduous hardwood"] },

  // Animalia
  { id: "monochamus", common: "White-spotted Sawyer Beetle", binomial: "Monochamus scutellatus", kingdom: "animalia", grp: "Kingdom Animalia · Arthropoda · Insecta (Coleoptera)", image: "/organisms/monochamus.png", alt: "Photograph of male and female White-spotted Sawyer Beetle (Monochamus scutellatus)", caption: "University of Maine Cooperative Extension. (n.d.). Sawyer beetles [Photograph]. https://extension.umaine.edu/home-and-garden-ipm/fact-sheets/common-name-listing/sawyer-beetles/", sort: 5,
    diagnostic: "An <b>insect</b> (arthropod): a jointed <b>exoskeleton</b> of <b>chitin</b>, breathing through <b>spiracles</b> and <b>tracheae</b>, with an <b>open circulatory system</b>.",
    traits: ["Invertebrate <b>arthropod</b> (insect)", "<b>Exoskeleton</b> of <b>chitin</b>", "Breathes via <b>spiracles</b>/<b>tracheae</b>", "<b>Open circulatory system</b>"] },
  { id: "salvelinus", common: "Brook Trout", binomial: "Salvelinus fontinalis", kingdom: "animalia", grp: "Kingdom Animalia · Chordata · Actinopterygii (fish)", image: "/organisms/salvelinus.png", alt: "Photograph of Brook Trout (Salvelinus fontinalis)", caption: "How to Catch Any Fish. (n.d.). Brook trout [Photograph]. https://www.howtocatchanyfish.com/brook-trout", sort: 6,
    diagnostic: "A <b>fish</b> (vertebrate): breathes with <b>gills</b>, has a <b>two-chambered heart</b> with single-loop circulation, and reproduces by <b>external fertilization</b> in cold streams.",
    traits: ["Vertebrate <b>fish</b>", "Breathes with <b>gills</b> (countercurrent)", "<b>Two-chambered heart</b>", "<b>External fertilization</b>"] },
  { id: "lithobates", common: "Wood Frog", binomial: "Lithobates sylvaticus", kingdom: "animalia", grp: "Kingdom Animalia · Chordata · Amphibia (Anura)", image: "/organisms/lithobates.png", alt: "Photograph of Wood Frog (Lithobates sylvaticus)", caption: "Wikipedia. (n.d.). Wood frog [Photograph]. https://en.wikipedia.org/wiki/Wood_frog", sort: 7,
    diagnostic: "An <b>amphibian</b>: moist, scaleless <b>skin</b> for <b>cutaneous gas exchange</b>, a <b>three-chambered heart</b>, <b>external fertilization</b>, and <b>metamorphosis</b> from a tadpole.",
    traits: ["Vertebrate <b>amphibian</b>", "Moist <b>skin</b> for gas exchange", "<b>Three-chambered heart</b>", "<b>External fertilization</b>; freeze-tolerant"] },
  { id: "alces", common: "Moose", binomial: "Alces alces", kingdom: "animalia", grp: "Kingdom Animalia · Chordata · Mammalia (Artiodactyla)", image: "/organisms/alces.png", alt: "Photograph of two Moose (Alces alces) on a snowy trail", caption: "Visit Big Sky. (n.d.). Moose [Photograph]. https://www.visitbigsky.com/articles/post/interesting-facts-about-moose/", sort: 8,
    diagnostic: "A <b>mammal</b>, and the largest animal in Algonquin: it breathes with alveolar <b>lungs</b>, has a <b>four-chambered heart</b>, uses <b>internal fertilization</b>, and is <b>endothermic</b>.",
    traits: ["Vertebrate <b>mammal</b>", "<b>Lungs</b> with <b>alveoli</b>; <b>four-chambered heart</b>", "<b>Internal fertilization</b>; live birth", "<b>Endothermic</b>; browsing herbivore"] },
  { id: "gavia", common: "Common Loon", binomial: "Gavia immer", kingdom: "animalia", grp: "Kingdom Animalia · Chordata · Aves (Gaviiformes)", image: "/organisms/gavia.png", alt: "Photograph of an adult Common Loon (Gavia immer) with a black head and white-checkered back swimming on a lake beside two brown chicks", caption: "American Bird Conservancy. (n.d.). Common loon [Photograph]. https://abcbirds.org/birds/common-loon/", sort: 9,
    diagnostic: "A <b>bird</b> (<b>Aves</b>): a feathered vertebrate with a toothless <b>beak</b> that breathes with <b>lungs</b>, runs a <b>four-chambered heart</b> with <b>double circulation</b>, and lays hard-shelled <b>eggs</b>. This <b>endothermic</b> diver is a familiar sight on Algonquin's lakes.",
    traits: ["Vertebrate <b>bird</b> (<b>Aves</b>)", "<b>Feathers</b>; toothless <b>beak</b>", "<b>Lungs</b>; <b>four-chambered heart</b>", "Lays <b>eggs</b>; <b>endothermic</b>"] },

  // Fungi
  { id: "trametes", common: "Turkey Tail", binomial: "Trametes versicolor", kingdom: "fungi", grp: "Kingdom Fungi · Basidiomycota · Polyporales", image: "/organisms/trametes.png", alt: "Photograph of Turkey Tail (Trametes versicolor) brackets on wood", caption: "The Sophisticated Caveman. (n.d.). Turkey tail mushrooms [Photograph]. https://www.thesophisticatedcaveman.com/turkey-tail-mushrooms/", sort: 10,
    diagnostic: "A <b>multicellular</b> fungus (<b>chitin</b> walls) growing as a thin, banded <b>bracket</b> on dead wood; a <b>saprotroph</b> releasing <b>spores</b> from <b>pores</b>.",
    traits: ["<b>Multicellular</b> fungus (<b>chitin</b> walls)", "<b>Saprotroph</b> / wood-decomposer", "Banded, fan-shaped bracket", "<b>Spores</b> from pores (a <b>polypore</b>)"] },
  { id: "inonotus", common: "Chaga", binomial: "Inonotus obliquus", kingdom: "fungi", grp: "Kingdom Fungi · Basidiomycota · Hymenochaetales", image: "/organisms/inonotus.png", alt: "Photograph of a Chaga (Inonotus obliquus) conk on a birch trunk", caption: "Swallowtail. (n.d.). Chaga [Photograph]. https://swallowtail.ca/how-to-make-chaga-tea/", sort: 11,
    diagnostic: "A fungus forming a hard, black, charcoal-like <b>sterile conk</b> on living birch; a parasite/<b>saprotroph</b> with <b>chitin</b> walls.",
    traits: ["<b>Multicellular</b> fungus (<b>chitin</b> walls)", "Black, cracked <b>conk</b> on birch", "Parasite that later decays wood", "Reproduces by <b>spores</b>"] },
  { id: "amanita", common: "Fly Agaric", binomial: "Amanita muscaria", kingdom: "fungi", grp: "Kingdom Fungi · Basidiomycota · Agaricales", image: "/organisms/amanita.png", alt: "Photograph of Fly Agaric (Amanita muscaria) with a red, white-warted cap", caption: "Encyclopaedia Britannica. (n.d.). Fly agaric [Photograph]. https://www.britannica.com/science/fly-agaric", sort: 12,
    diagnostic: "A classic <b>cap-and-stalk</b> mushroom with a red <b>cap</b>, white <b>warts</b>, white <b>gills</b>, and a basal <b>volva</b>; a <b>mycorrhizal</b> fungus.",
    traits: ["<b>Multicellular</b> fungus (<b>chitin</b> walls)", "Red cap with white <b>warts</b>; white <b>gills</b>", "Forms <b>mycorrhizae</b> with tree roots", "Toxic (muscimol / ibotenic acid)"] },
  { id: "cantharellus", common: "Chanterelle", binomial: "Cantharellus cibarius", kingdom: "fungi", grp: "Kingdom Fungi · Basidiomycota · Cantharellales", image: "/organisms/cantharellus.png", alt: "Photograph of Chanterelle (Cantharellus cibarius) mushrooms", caption: "Zombie Myco. (n.d.). Chanterelle mushrooms [Photograph]. https://zombiemyco.com/blogs/mushrooms/chanterelle-mushrooms-are-they-safe-to-forage", sort: 13,
    diagnostic: "A yellow, <b>funnel-shaped</b> mushroom with blunt, forking <b>false gills</b> (ridges); a <b>mycorrhizal</b> partner of forest trees.",
    traits: ["<b>Multicellular</b> fungus (<b>chitin</b> walls)", "Yellow, funnel/trumpet shape", "Blunt ridges (<b>false gills</b>)", "<b>Mycorrhizal</b> with trees"] },
  { id: "armillaria", common: "Honey Mushroom", binomial: "Armillaria mellea", kingdom: "fungi", grp: "Kingdom Fungi · Basidiomycota · Agaricales", image: "/organisms/armillaria.png", alt: "Photograph of a dense cluster of glossy, honey-yellow Honey Mushrooms (Armillaria mellea) growing on the forest floor", caption: "Wikipedia. (n.d.). Armillaria mellea [Photograph]. https://en.wikipedia.org/wiki/Armillaria_mellea", sort: 14,
    diagnostic: "A <b>multicellular</b> fungus (<b>chitin</b> walls) with honey-brown <b>cap-and-stalk</b> bodies in <b>clusters</b> on wood and roots; a <b>parasite</b>/<b>saprotroph</b> that spreads by black root-like <b>rhizomorphs</b>.",
    traits: ["<b>Multicellular</b> fungus (<b>chitin</b> walls)", "Honey-brown caps in <b>clusters</b>; a stem <b>ring</b>", "<b>Parasite</b>/<b>saprotroph</b> on wood and roots", "Spreads by <b>rhizomorphs</b>; <b>spores</b> from <b>gills</b>"] },

  // Prokaryotes & Protists
  { id: "nitrosomonas", common: "Nitrifying Bacterium", binomial: "Nitrosomonas europaea", kingdom: "micro", grp: "Domain Bacteria · Pseudomonadota (Proteobacteria)", image: "/organisms/nitrosomonas.png", alt: "Micrograph of rod-shaped Nitrifying Bacteria (Nitrosomonas europaea)", caption: "Aquatic Creations Group. (n.d.). Nitrifying bacteria [Photograph]. https://aquaticcreationsgroup.com/nitrogen-cycle-overview/", sort: 15,
    diagnostic: "<b>Prokaryotic</b> cell with a <b>peptidoglycan</b> wall; a <b>chemoautotroph</b> that oxidizes ammonia to nitrite, driving the soil <b>nitrogen cycle</b>.",
    traits: ["<b>Prokaryotic</b> (no membrane-bound nucleus)", "Cell wall contains <b>peptidoglycan</b>", "<b>Chemoautotroph</b> (energy from ammonia)", "Reproduces by <b>binary fission</b>"] },
  { id: "methanobrevibacter", common: "Methanogen", binomial: "Methanobrevibacter smithii", kingdom: "micro", grp: "Domain Archaea · Euryarchaeota", image: "/organisms/methanobrevibacter.png", alt: "Micrograph of Methanogen (Methanobrevibacter smithii) cells", caption: "Study.com. (n.d.). Methanogens [Photograph]. https://study.com/academy/lesson/methanogens-definition-classification-examples.html", sort: 16,
    diagnostic: "A <b>prokaryotic</b> archaeon whose wall lacks <b>peptidoglycan</b>; an anaerobic <b>methanogen</b> that releases methane in the guts of herbivores such as moose.",
    traits: ["<b>Prokaryotic</b> archaeon", "Cell wall <b>lacks peptidoglycan</b>", "Strict <b>anaerobe</b>", "Produces <b>methane</b> (CH₄) as waste"] },
  { id: "euglena", common: "Euglena", binomial: "Euglena viridis", kingdom: "micro", grp: "Domain Eukarya · Kingdom Protista · Euglenozoa", image: "/organisms/euglena.png", alt: "Micrograph of Euglena (Euglena viridis) cells with green chloroplasts", caption: "Wikipedia. (n.d.). Euglena [Photograph]. https://en.wikipedia.org/wiki/Euglena", sort: 17,
    diagnostic: "A <b>unicellular</b> eukaryote that is <b>photosynthetic</b> (green <b>chloroplasts</b>); swims with a <b>flagellum</b> and detects light with a red <b>eyespot</b>.",
    traits: ["<b>Unicellular</b> eukaryote (protist)", "<b>Photosynthetic</b>, with <b>chloroplasts</b>", "Moves with a <b>flagellum</b>", "Light-sensing <b>eyespot</b>"] },
  { id: "amoeba", common: "Amoeba", binomial: "Amoeba proteus", kingdom: "micro", grp: "Domain Eukarya · Kingdom Protista · Amoebozoa", image: "/organisms/amoeba.png", alt: "Micrograph of an Amoeba (Amoeba proteus) with pseudopodia", caption: "Wikipedia. (n.d.). Amoeba (genus) [Photograph]. https://en.wikipedia.org/wiki/Amoeba_(genus)", sort: 18,
    diagnostic: "A <b>unicellular</b>, non-photosynthetic eukaryote; a <b>heterotroph</b> that moves and engulfs prey with <b>pseudopodia</b> by <b>phagocytosis</b>.",
    traits: ["<b>Unicellular</b> eukaryote (protist)", "<b>Heterotroph</b> that engulfs food (<b>phagocytosis</b>)", "Moves using <b>pseudopodia</b>", "No fixed body shape"] },
  { id: "physarum", common: "Slime Mould", binomial: "Physarum polycephalum", kingdom: "micro", grp: "Domain Eukarya · Kingdom Protista · Myxogastria", image: "/organisms/physarum.png", alt: "Photograph of yellow Slime Mould (Physarum polycephalum) on grass", caption: "Australian Environmental Education. (n.d.). Slime moulds [Photograph]. https://www.australianenvironmentaleducation.com.au/education-resources/slime-moulds-natures-mysterious-decomposers/", sort: 19,
    diagnostic: "A <b>saprotrophic</b> protist (not a true fungus) that creeps across the forest floor as a bright, multinucleate <b>plasmodium</b> feeding on decay.",
    traits: ["Eukaryotic protist (<b>not</b> a true fungus)", "<b>Saprotroph</b> on decaying matter", "Forms a creeping <b>plasmodium</b>", "Reproduces by <b>spores</b>"] },
];

/* --- Key tree (19 couplets). a_target / b_target are node ids or organism ids. --- */
export const seedNodes: KeyNode[] = [
  { id: "q1", num: "1", region: "root", sort: 0, short: "Eukaryotic cells?",
    question: "Are the organism's cells <b>eukaryotic</b>, with a true, membrane-bound <b>nucleus</b> and organelles?",
    a_short: "Yes, eukaryotic", a_label: "Yes, the cells are <b>eukaryotic</b> (a true nucleus is present)", a_target: "q3",
    b_short: "No, prokaryotic", b_label: "No, the cells are <b>prokaryotic</b>, with DNA loose in the <b>cytoplasm</b>", b_target: "q2" },
  { id: "q2", num: "2", region: "micro", sort: 1, short: "Peptidoglycan wall?",
    question: "Does the cell wall contain <b>peptidoglycan</b>, and does the cell gain energy by <b>chemosynthesis</b> (oxidizing ammonia)?",
    a_short: "Yes, peptidoglycan", a_label: "Yes, a <b>peptidoglycan</b> wall, and a <b>chemoautotroph</b> of the nitrogen cycle", a_target: "nitrosomonas",
    b_short: "No, a methanogen", b_label: "No <b>peptidoglycan</b>, and an anaerobic <b>methanogen</b> that produces methane", b_target: "methanobrevibacter" },
  { id: "q3", num: "3", region: "root", sort: 2, short: "Unicellular?",
    question: "Is the organism <b>unicellular</b> (a single cell) rather than <b>multicellular</b>?",
    a_short: "Yes, unicellular", a_label: "Yes, it is <b>unicellular</b> (a single cell)", a_target: "q4",
    b_short: "No, multicellular", b_label: "No, it is <b>multicellular</b>, built from many specialized cells", b_target: "q6" },
  { id: "q4", num: "4", region: "micro", sort: 3, short: "Photosynthetic?",
    question: "Is the single cell <b>photosynthetic</b>, containing <b>chloroplasts</b> and making its own food (an <b>autotroph</b>)?",
    a_short: "Yes, an autotroph", a_label: "Yes, it is <b>photosynthetic</b>: it swims with a <b>flagellum</b> and has a red <b>eyespot</b>", a_target: "euglena",
    b_short: "No, a heterotroph", b_label: "No, it is a <b>heterotroph</b>", b_target: "q5" },
  { id: "q5", num: "5", region: "micro", sort: 4, short: "Feeds by pseudopodia?",
    question: "Does the cell feed by engulfing prey with <b>pseudopodia</b> (a <b>heterotroph</b>), rather than absorbing decay?",
    a_short: "Yes, pseudopodia", a_label: "Yes, an ingestive <b>heterotroph</b> that moves by <b>pseudopodia</b> (<b>phagocytosis</b>)", a_target: "amoeba",
    b_short: "No, a saprotroph", b_label: "No, a <b>saprotroph</b> that creeps along as a multinucleate <b>plasmodium</b>", b_target: "physarum" },
  { id: "q6", num: "6", region: "fungi", sort: 5, short: "Saprotroph fungus?",
    question: "Is the organism a <b>saprotroph</b> with cell walls of <b>chitin</b> that feeds by <b>absorption</b> (a fungus)?",
    a_short: "Yes, a fungus", a_label: "Yes, a <b>fungus</b> with <b>chitin</b> walls, <b>absorptive</b> feeding, and <b>spores</b>", a_target: "q7",
    b_short: "No, a plant or animal", b_label: "No, either a <b>plant</b> or an <b>animal</b>", b_target: "q9" },
  { id: "q7", num: "7", region: "fungi", sort: 6, short: "Bracket on wood?",
    question: "Does the fungus grow as a tough <b>bracket</b> (shelf) on wood, rather than a fleshy <b>cap-and-stalk</b> mushroom?",
    a_short: "Yes, a bracket", a_label: "Yes, a woody or leathery <b>bracket fungus</b>", a_target: "q8",
    b_short: "No, capped or funnel", b_label: "No, a fleshy <b>cap</b> or <b>funnel</b> mushroom", b_target: "q8b" },
  { id: "q8", num: "8", region: "fungi", sort: 7, short: "Thin, banded, multi-coloured?",
    question: "Is the bracket thin and banded with concentric, multi-coloured zones (like a fanned tail), with <b>pores</b> beneath?",
    a_short: "Yes, banded", a_label: "Yes, a thin, banded, fan-shaped bracket with <b>pores</b> (a <b>polypore</b>)", a_target: "trametes",
    b_short: "No, a black birch mass", b_label: "No, a hard, black, charcoal-like <b>sterile conk</b> on birch", b_target: "inonotus" },
  { id: "q8b", num: "8b", region: "fungi", sort: 8, short: "True gills or false gills?",
    question: "Does the fleshy mushroom bear true, blade-like <b>gills</b> beneath the cap, rather than blunt, forking ridges (<b>false gills</b>)?",
    a_short: "Yes, true gills", a_label: "Yes, a gilled <b>cap-and-stalk</b> mushroom", a_target: "q8c",
    b_short: "No, false gills", b_label: "No, a yellow, <b>funnel-shaped</b> body with blunt, forking <b>false gills</b>", b_target: "cantharellus" },
  { id: "q8c", num: "8c", region: "fungi", sort: 9, short: "Red warty cap with a volva?",
    question: "Does the gilled mushroom have a bright red <b>cap</b> dotted with white <b>warts</b> and a cup-like <b>volva</b> at its base, rather than honey-brown caps clustered on wood?",
    a_short: "Yes, red warty cap", a_label: "Yes, a red cap with white <b>warts</b>, white <b>gills</b>, and a basal <b>volva</b> (a <b>mycorrhizal</b> fungus)", a_target: "amanita",
    b_short: "No, honey clusters", b_label: "No, honey-brown caps in <b>clusters</b> on wood and roots, with a stem <b>ring</b> (a <b>parasite</b> and <b>saprotroph</b>)", b_target: "armillaria" },
  { id: "q9", num: "9", region: "split", sort: 10, short: "Photosynthetic plant?",
    question: "Is the organism a <b>photosynthetic</b> <b>plant</b> (makes food in <b>chloroplasts</b>; cell walls of <b>cellulose</b>)?",
    a_short: "Yes, a plant", a_label: "Yes, a <b>plant</b> (an <b>autotroph</b>)", a_target: "q10",
    b_short: "No, an animal", b_label: "No, an <b>animal</b> (an ingestive <b>heterotroph</b>)", b_target: "q14" },
  { id: "q10", num: "10", region: "plant", sort: 11, short: "Vascular tissue?",
    question: "Does the plant have <b>vascular tissue</b> (<b>xylem</b> and <b>phloem</b>) to transport water and food?",
    a_short: "Yes, vascular", a_label: "Yes, a <b>vascular</b> plant", a_target: "q11",
    b_short: "No, non-vascular", b_label: "No, a <b>non-vascular</b> plant that absorbs water directly and reproduces by <b>spores</b>", b_target: "sphagnum" },
  { id: "q11", num: "11", region: "plant", sort: 12, short: "Reproduces by seeds?",
    question: "Does the vascular plant reproduce by <b>seeds</b> rather than by <b>spores</b>?",
    a_short: "Yes, seeds", a_label: "Yes, a <b>seed plant</b>", a_target: "q12",
    b_short: "No, spores", b_label: "No, a <b>seedless vascular</b> plant (a <b>pteridophyte</b>) with <b>spores</b> in <b>sori</b>", b_target: "matteuccia" },
  { id: "q12", num: "12", region: "plant", sort: 13, short: "Seeds enclosed in fruit?",
    question: "Are the <b>seeds</b> enclosed in a <b>fruit / ovary</b> (an <b>angiosperm</b>), rather than exposed on <b>cones</b>?",
    a_short: "Yes, enclosed", a_label: "Yes, a <b>flowering plant</b> (<b>angiosperm</b>) with seeds enclosed in a <b>fruit</b>", a_target: "q13",
    b_short: "No, cones", b_label: "No, a <b>gymnosperm</b> with naked seeds on woody <b>cones</b> and needle leaves", b_target: "pinus" },
  { id: "q13", num: "13", region: "plant", sort: 14, short: "Parallel leaf veins?",
    question: "Does the flowering plant have <b>parallel leaf veins</b> and flower parts in threes (a <b>monocot</b>)?",
    a_short: "Yes, monocot", a_label: "Yes, a <b>monocot</b> with <b>parallel venation</b> and three-part flowers", a_target: "trillium",
    b_short: "No, dicot", b_label: "No, a <b>dicot</b> with broad leaves and <b>net-like (reticulate) venation</b>", b_target: "acer" },
  { id: "q14", num: "14", region: "animal", sort: 15, short: "Tracheae + open circulation?",
    question: "Does the animal breathe through <b>spiracles</b> and <b>tracheae</b> with an <b>open circulatory system</b> (an <b>arthropod / insect</b>)?",
    a_short: "Yes, an insect", a_label: "Yes, an <b>insect</b> with <b>tracheal</b> breathing, <b>open circulation</b>, and jointed legs", a_target: "monochamus",
    b_short: "No, a vertebrate", b_label: "No, a <b>vertebrate</b>", b_target: "q15" },
  { id: "q15", num: "15", region: "animal", sort: 16, short: "Gills, 2-chambered heart?",
    question: "Does the vertebrate breathe with <b>gills</b> and have a <b>two-chambered heart</b> with single-loop circulation (a fish)?",
    a_short: "Yes, a fish", a_label: "Yes, a <b>fish</b> with <b>gills</b>, a <b>two-chambered heart</b>, and <b>external fertilization</b>", a_target: "salvelinus",
    b_short: "No, a tetrapod", b_label: "No, a <b>tetrapod</b>", b_target: "q16" },
  { id: "q16", num: "16", region: "animal", sort: 17, short: "Moist skin, 3-chambered heart?",
    question: "Does the animal have moist <b>skin</b> for <b>cutaneous gas exchange</b>, a <b>three-chambered heart</b>, and <b>external fertilization</b> (an <b>amphibian</b>)?",
    a_short: "Yes, an amphibian", a_label: "Yes, an <b>amphibian</b> with moist skin, a <b>three-chambered heart</b>, <b>external fertilization</b>, and <b>metamorphosis</b>", a_target: "lithobates",
    b_short: "No, an amniote", b_label: "No, an <b>amniote</b>: a land vertebrate with <b>lungs</b>, a <b>four-chambered heart</b>, and <b>internal fertilization</b>", b_target: "q17" },
  { id: "q17", num: "17", region: "animal", sort: 18, short: "Feathers or fur?",
    question: "Is the amniote covered in <b>feathers</b> with a toothless <b>beak</b>, laying hard-shelled <b>eggs</b> (a <b>bird</b>), rather than having <b>fur/hair</b> and <b>mammary glands</b> that nurse live young (a <b>mammal</b>)?",
    a_short: "Yes, a bird", a_label: "Yes, a <b>bird</b> (<b>Aves</b>) with <b>feathers</b>, a <b>beak</b>, and <b>eggs</b>; <b>endothermic</b>", a_target: "gavia",
    b_short: "No, a mammal", b_label: "No, a <b>mammal</b> with <b>fur/hair</b>, <b>mammary glands</b>, and live birth; <b>endothermic</b>", b_target: "alces" },
];

export const seedConcepts: { heading: string; body: string; sort: number }[] = [
  { sort: 0, heading: "Taxonomy & Classification",
    body: "Sorting twenty very different organisms starts with <b>taxonomy</b>, the science of naming and classifying life (Di Giuseppe et al., 2011). Every species sits inside a nested ranking that runs from <b>Domain</b> through <b>Kingdom</b>, <b>Phylum</b>, <b>Class</b>, <b>Order</b>, <b>Family</b>, and <b>Genus</b> down to <b>Species</b>, and each one gets a two-word <b>binomial name</b> in italics: a capitalized <b>genus</b> and a lowercase species epithet, as in <i>Acer saccharum</i>. This key works its way down using the same kinds of clues. Its first question is the deepest divide in biology, splitting the <b>prokaryotes</b> from the <b>eukaryotes</b>. The <b>bacterium</b> <i>Nitrosomonas europaea</i> and the <b>archaeon</b> <i>Methanobrevibacter smithii</i> are prokaryotes with no membrane-bound <b>nucleus</b>, whereas eukaryotes like protists, fungi, plants, and animals keep their DNA sealed inside one. After that the questions get more concrete. Is the organism <b>unicellular</b>, like a single <i>Euglena</i> cell, or <b>multicellular</b>, like a Sugar Maple? What is its <b>morphology</b>, and what <b>habitat</b> does it fill across Algonquin's forests, lakes, and bogs (Ontario Parks, 2023)? And how does it feed? An <b>autotroph</b> such as a plant builds its own food, a <b>heterotroph</b> such as the moose eats other organisms, and a <b>saprotroph</b> such as <i>Trametes versicolor</i> absorbs nutrients straight from dead wood." },
  { sort: 1, heading: "Gas Exchange in Plants",
    body: "A plant never actually breathes. It takes in the carbon dioxide it needs for <b>photosynthesis</b>, and releases the oxygen it produces, entirely by <b>diffusion</b> (Raven et al., 2020). How it manages that depends on its size. <i>Sphagnum capillifolium</i> is <b>non-vascular</b> and only a few cells thick, so gas crosses its surface directly. A large <b>vascular</b> plant is far too bulky for that and relies on dedicated pores. In a leaf those pores are the <b>stomata</b>, while woody stems use <b>lenticels</b> instead. The inside of a broad-leaf <b>dicot</b> like <i>Acer saccharum</i> is arranged around the light: most of its <b>chloroplasts</b> sit in the tall, column-shaped cells of the <b>palisade mesophyll</b> near the upper surface, where the light is strongest. Beneath them lies the <b>spongy mesophyll</b>, a loose layer riddled with air spaces. Carbon dioxide slips in through the <b>stomata</b>, <b>diffuses</b> through those spaces until it reaches the <b>chloroplasts</b>, and oxygen and water vapour leave by the same route. A <b>monocot</b> like <i>Trillium grandiflorum</i> uses <b>stomata</b> too, but its leaf shows <b>parallel venation</b> and its mesophyll is not divided as neatly into two layers (Di Giuseppe et al., 2011)." },
  { sort: 2, heading: "Transport in Plants",
    body: "<b>Diffusion</b> is fast over microscopic distances and useless over the height of a maple, so <b>vascular plants</b> move materials through tubes instead. It begins at the roots, where water is drawn in by <b>osmosis</b>, crossing a <b>semipermeable</b> membrane from high <b>water potential</b> toward low (Raven et al., 2020). The <b>xylem</b> then carries that water and its dissolved minerals upward, and nothing actually pumps it: as water evaporates from the leaves during <b>transpiration</b>, cohesion between the molecules drags the whole column up behind it, the idea behind <b>cohesion–tension</b>. The <b>phloem</b> handles the opposite trip, moving sugar from where it is made to where it is needed in a process called <b>translocation</b>, from <b>source</b> to <b>sink</b>. Both tissues run through <b>monocots</b> like <i>Trillium grandiflorum</i> and <b>dicots</b> like <i>Acer saccharum</i>; the clearest difference is how their <b>vascular bundles</b> are arranged. <i>Sphagnum</i> does without all of this. Being <b>non-vascular</b>, it has no <b>xylem</b> or <b>phloem</b>, stays low to the ground, and shifts water from cell to cell by plain <b>diffusion</b> and <b>osmosis</b> (Di Giuseppe et al., 2011)." },
  { sort: 3, heading: "Gas Exchange in Animals",
    body: "Animals live under the same rule as plants: gas only crosses a surface that is thin, moist, and <b>semipermeable</b>, and it crosses by <b>diffusion</b> (Raven et al., 2020). What differs is the machinery behind that surface. The sawyer beetle, an <b>insect</b> (<i>Monochamus scutellatus</i>), skips blood delivery entirely and pipes air straight to its cells through branching <b>tracheae</b> that open at pores called <b>spiracles</b>. The Brook Trout (<i>Salvelinus fontinalis</i>), a <b>fish</b>, drives water over its <b>gills</b> and uses <b>countercurrent exchange</b> to pull the dissolved oxygen out of it. The Wood Frog (<i>Lithobates sylvaticus</i>), an <b>amphibian</b>, does much of its breathing straight through its damp, <b>semipermeable</b> <b>skin</b>, a route known as <b>cutaneous</b> exchange. The Moose (<i>Alces alces</i>), a <b>mammal</b>, is the most active breather of the group. Its <b>ventilation</b> keeps fresh air moving into the <b>lungs</b> so oxygen can <b>diffuse</b> across the <b>semipermeable</b> walls of the <b>alveoli</b> and into the <b>capillaries</b> wrapped tightly around them, with carbon dioxide leaving the same way (Di Giuseppe et al., 2011)." },
  { sort: 4, heading: "Transport in Animals",
    body: "Moving all that oxygen around is the job of a <b>circulatory system</b>, and the ones in this key grow steadily more capable. The beetle runs an <b>open circulatory system</b>: its heart pumps <b>hemolymph</b> into open body spaces to wash over the organs, then lets it drain back. <b>Vertebrates</b> seal their blood inside vessels, giving a <b>closed circulatory system</b>. In the Brook Trout that circuit is simple, since its <b>two-chambered heart</b> pushes blood around the body on a <b>single</b> loop before it returns, which is <b>single circulation</b> (a <b>single closed</b> system). Mammals and birds take this further. The Moose and the Common Loon both have a <b>four-chambered heart</b> that keeps oxygen-rich and oxygen-poor blood completely separate and passes it through the heart twice each lap, giving <b>double circulation</b> (a <b>double closed</b> system) rather than the fish's single loop. The Wood Frog falls in between, with a <b>three-chambered heart</b> that only partly divides the two streams. Wherever the blood travels, the real exchange happens at the <b>capillaries</b>, where nutrients and gases slip into the tissues by <b>diffusion</b> and water shifts between blood and cells by <b>osmosis</b> across their <b>semipermeable</b> walls (Raven et al., 2020)." },
  { sort: 5, heading: "Reproductive Strategies",
    body: "Reproduction in Algonquin ranges from a single cell splitting in two to a cow moose raising one calf, and it covers both <b>asexual reproduction</b> and <b>sexual reproduction</b> (Government of Canada, 2023). The simplest method is <b>binary fission</b>, where a cell copies its DNA and divides into two identical cells; the <b>bacterium</b> <i>Nitrosomonas europaea</i>, the <b>archaeon</b> <i>Methanobrevibacter smithii</i>, and the protist <i>Amoeba proteus</i> all reproduce this way. Larger organisms clone themselves through other routes. A torn piece of <i>Sphagnum</i> can regrow into a whole new plant by <b>fragmentation</b>, and many yeasts and <b>fungi</b> pinch off small copies of themselves by <b>budding</b>. Plants can also skip seeds altogether and use <b>vegetative propagation</b>, sending up clones from runners, rhizomes, and stray root pieces. Then come the <b>spores</b>, the dust-fine dispersal cells of <b>mosses</b>, the <b>fern</b> <i>Matteuccia struthiopteris</i> (which packs them into clusters called <b>sori</b>), and fungi such as <i>Amanita muscaria</i>. Sexual reproduction shows just as much range: the Brook Trout and Wood Frog spawn in water by <b>external fertilization</b>, while the Moose and Common Loon use <b>internal fertilization</b>, after which the loon lays a small clutch of <b>eggs</b> and the moose gives birth to live young, the classic <b>K-selected</b> strategy of a few well-protected offspring (Di Giuseppe et al., 2011)." },
];

export const seedReferences: { entry: string; sort: number }[] = [
  { sort: 0, entry: "Di Giuseppe, M., Vavitsas, A., Fraser, D., Ku, D., Lisser, B., &amp; Vucic, S. (2011). <i>Nelson biology 11</i>. Nelson Education." },
  { sort: 1, entry: "Government of Canada. (2023). <i>Species profiles</i>. Canadian Wildlife Service. https://www.canada.ca" },
  { sort: 2, entry: "Government of Ontario. (n.d.). <i>Ontario's forest regions: Great Lakes–St. Lawrence forest</i>. Ministry of Natural Resources and Forestry. https://www.ontario.ca" },
  { sort: 3, entry: "Ontario Parks. (2023). <i>Algonquin Provincial Park</i>. Ontario Parks. https://www.ontarioparks.com/park/algonquin" },
  { sort: 4, entry: "Raven, P. H., Johnson, G. B., Mason, K. A., Losos, J. B., &amp; Duncan, T. (2020). <i>Biology</i> (12th ed.). McGraw-Hill Education." },
];

export const seedMeta: SiteMetaData = {
  siteTitle: "A Dichotomous Key to 20 Organisms of Algonquin Provincial Park",
  subtitle: "Great Lakes–St. Lawrence Forest Region · SBI3U Biology (Ontario)",
  ecozone: "Great Lakes–St. Lawrence Forest Region · Algonquin Provincial Park, Ontario",
  introHeading: "A field key to the living things of Algonquin",
  introBlurb:
    "This is an interactive <b>dichotomous key</b> to the living things of the <b>Great Lakes–St. Lawrence Forest Region</b> (Government of Ontario, n.d.), built around the mixed forests, cold lakes, and bogs of <b>Algonquin Provincial Park</b> in Ontario (Ontario Parks, 2023). A <b>dichotomous key</b> works by asking one either/or question at a time: at each fork you choose the description that fits and follow that branch, narrowing things down until a single organism is left. This one runs through <b>20 organisms</b> from every <b>kingdom</b> of life, leaning on the SBI3U ideas of <b>taxonomy</b>, <b>gas exchange</b>, <b>transport</b>, and <b>reproduction</b> along the way (Di Giuseppe et al., 2011).",
  howToHeading: "How to use the tree",
  howTo: [
    "Start at the root node, <b>Couplet 1</b>, on the left of the tree.",
    "Read each <b>question</b> and click the choice, <b>a</b> or <b>b</b>, that matches your organism. The bolded words are the diagnostic <b>key terms</b>.",
    "The chosen branch <b>lights up in copper</b> and the breadcrumb records your path until you reach a <b>species endpoint</b>.",
    "<b>Hover</b> or <b>focus</b> any node to enlarge it and read the full detail. On a phone, use the step-through version below the tree.",
  ],
  referencesNote:
    "References are listed alphabetically in <b>APA style</b>. <b>In-text citations</b> (author, year) appear throughout the intro and Biology Concepts sections.",
  footer:
    "Interactive dichotomous key · <b>SBI3U Biology</b> · Great Lakes–St. Lawrence Forest Region, Algonquin Provincial Park.",
};
