/* ===========================================================================
   keyData.ts — SEED DATA
   ---------------------------------------------------------------------------
   The database is seeded from the arrays below on first run. After that the
   whole site reads from Postgres, so admin edits are live. HTML is allowed in
   text fields (<b> to bold key terms, <i> for italics).
   =========================================================================== */
import type {
  Organism,
  KeyNode,
  SiteMetaData,
} from "./types";

/* --- 18 organisms (sort defines gallery order within each kingdom) --- */
export const seedOrganisms: Organism[] = [
  // Plantae
  { id: "sphagnum", common: "Sphagnum Moss", binomial: "Sphagnum capillifolium", kingdom: "plantae", grp: "Kingdom Plantae · Bryophyta (mosses)", image: "/organisms/sphagnum.png", alt: "Photograph of a dense carpet of Sphagnum Moss (Sphagnum capillifolium)", caption: "Gardening Know How. (n.d.). Sphagnum moss [Photograph]. https://www.gardeningknowhow.com/garden-how-to/soil-fertilizers/sphagnum-moss-vs-sphagnum-peat-moss.htm", sort: 0,
    diagnostic: "A <b>non-vascular</b> plant (bryophyte) with no <b>xylem</b> or <b>phloem</b>; it absorbs water directly and reproduces by <b>spores</b>, forming the <b>peat</b> of Algonquin's bogs.",
    traits: ["<b>Non-vascular</b> (no <b>xylem</b>/<b>phloem</b>)", "<b>Photosynthetic</b>, multicellular", "Absorbs water directly", "Reproduces by <b>spores</b>; builds <b>peat</b>"] },
  { id: "matteuccia", common: "Ostrich Fern", binomial: "Matteuccia struthiopteris", kingdom: "plantae", grp: "Kingdom Plantae · Polypodiopsida (ferns)", image: "/organisms/matteuccia.png", alt: "Photograph of Ostrich Fern (Matteuccia struthiopteris)", caption: "Dutch Growers. (n.d.). Ostrich fern [Photograph]. https://plants.dutchgrowers.net/11040004/Plant/1781/Ostrich_Fern/", sort: 1,
    diagnostic: "A <b>seedless vascular</b> plant (<b>pteridophyte</b>) with true <b>xylem</b> and <b>phloem</b> and large <b>fronds</b>; it reproduces by <b>spores</b> in <b>sori</b>, not seeds.",
    traits: ["<b>Vascular</b> but <b>seedless</b> (<b>pteridophyte</b>)", "Large feathery <b>fronds</b>", "<b>Spores</b> in <b>sori</b> under fronds", "True <b>xylem</b> and <b>phloem</b>"] },
  { id: "pinus", common: "Eastern White Pine", binomial: "Pinus strobus", kingdom: "plantae", grp: "Kingdom Plantae · Pinophyta (conifers)", image: "/organisms/pinus.png", alt: "Photograph of Eastern White Pine (Pinus strobus)", caption: "Sylvan Gardens Landscape. (n.d.). Eastern white pine [Photograph]. https://sylvangardenslandscape.com/plant-profile/eastern-white-pine-plant-profile/", sort: 2,
    diagnostic: "A <b>gymnosperm</b>: a <b>vascular</b> seed plant bearing \"naked\" <b>seeds</b> on woody <b>cones</b>, with needle leaves. Ontario's provincial tree.",
    traits: ["<b>Vascular</b> <b>gymnosperm</b>", "Naked <b>seeds</b> on woody <b>cones</b>", "Needle leaves in bundles of five", "<b>Wind-pollinated</b>; evergreen"] },
  { id: "trillium", common: "White Trillium", binomial: "Trillium grandiflorum", kingdom: "plantae", grp: "Kingdom Plantae · Angiosperms · Monocot (Liliopsida)", image: "/organisms/trillium.png", alt: "Photograph of White Trillium (Trillium grandiflorum)", caption: "Gardenia. (n.d.). Trillium grandiflorum (white trillium) [Photograph]. https://www.gardenia.net/plant/trillium-grandiflorum-white-trillium", sort: 3,
    diagnostic: "A <b>flowering plant</b> (<b>angiosperm</b>) whose <b>monocot</b> traits show in <b>parallel</b> leaf veins and flower parts in threes. Ontario's floral emblem.",
    traits: ["<b>Angiosperm</b> (seeds in an ovary)", "<b>Monocot</b>: <b>parallel</b> venation", "Flower parts in threes", "Spring woodland wildflower"] },
  { id: "acer", common: "Sugar Maple", binomial: "Acer saccharum", kingdom: "plantae", grp: "Kingdom Plantae · Angiosperms · Dicot (Magnoliopsida)", image: "/organisms/acer.png", alt: "Photograph of Sugar Maple (Acer saccharum) in autumn colour", caption: "Dutch Growers. (n.d.). Sugar maple [Photograph]. https://plants.dutchgrowers.net/11040004/Plant/22/Sugar_Maple/", sort: 4,
    diagnostic: "A <b>flowering plant</b> (<b>angiosperm</b>) with <b>dicot</b> traits: broad leaves with <b>net-like veins</b> and flower parts in fours/fives. Source of maple syrup.",
    traits: ["<b>Angiosperm</b> (seeds in a fruit)", "<b>Dicot</b>: <b>net-like</b> veins", "Broad lobed leaves; winged <b>samara</b>", "Deciduous hardwood"] },

  // Animalia
  { id: "monochamus", common: "White-spotted Sawyer Beetle", binomial: "Monochamus scutellatus", kingdom: "animalia", grp: "Kingdom Animalia · Arthropoda · Insecta (Coleoptera)", image: "/organisms/monochamus.png", alt: "Photograph of male and female White-spotted Sawyer Beetle (Monochamus scutellatus)", caption: "University of Maine Cooperative Extension. (n.d.). Sawyer beetles [Photograph]. https://extension.umaine.edu/home-and-garden-ipm/fact-sheets/common-name-listing/sawyer-beetles/", sort: 5,
    diagnostic: "An <b>insect</b> (arthropod): a jointed <b>exoskeleton</b> of <b>chitin</b>, breathing through <b>spiracles</b> and <b>tracheae</b>, with an <b>open circulatory system</b>.",
    traits: ["Invertebrate <b>arthropod</b> (insect)", "<b>Exoskeleton</b> of <b>chitin</b>", "Breathes via <b>spiracles</b>/<b>tracheae</b>", "<b>Open circulatory system</b>"] },
  { id: "salvelinus", common: "Brook Trout", binomial: "Salvelinus fontinalis", kingdom: "animalia", grp: "Kingdom Animalia · Chordata · Actinopterygii (fish)", image: "/organisms/salvelinus.png", alt: "Photograph of Brook Trout (Salvelinus fontinalis)", caption: "How to Catch Any Fish. (n.d.). Brook trout [Photograph]. https://www.howtocatchanyfish.com/brook-trout", sort: 6,
    diagnostic: "A <b>fish</b> (vertebrate): breathes with <b>gills</b>, has a <b>two-chambered heart</b> with single-loop circulation, and reproduces by <b>external fertilization</b> in cold streams.",
    traits: ["Vertebrate <b>fish</b>", "Breathes with <b>gills</b> (countercurrent)", "<b>Two-chambered heart</b>", "<b>External fertilization</b>"] },
  { id: "lithobates", common: "Wood Frog", binomial: "Lithobates sylvaticus", kingdom: "animalia", grp: "Kingdom Animalia · Chordata · Amphibia (Anura)", image: "/organisms/lithobates.png", alt: "Photograph of Wood Frog (Lithobates sylvaticus)", caption: "Wikipedia. (n.d.). Wood frog [Photograph]. https://en.wikipedia.org/wiki/Wood_frog", sort: 7,
    diagnostic: "An <b>amphibian</b>: moist, scaleless <b>skin</b> for <b>cutaneous gas exchange</b>, a <b>three-chambered heart</b>, <b>external fertilization</b>, and <b>metamorphosis</b> from a tadpole.",
    traits: ["Vertebrate <b>amphibian</b>", "Moist <b>skin</b> for gas exchange", "<b>Three-chambered heart</b>", "<b>External fertilization</b>; freeze-tolerant"] },
  { id: "alces", common: "Moose", binomial: "Alces alces", kingdom: "animalia", grp: "Kingdom Animalia · Chordata · Mammalia (Artiodactyla)", image: "/organisms/alces.png", alt: "Photograph of two Moose (Alces alces) on a snowy trail", caption: "Visit Big Sky. (n.d.). Moose [Photograph]. https://www.visitbigsky.com/articles/post/interesting-facts-about-moose/", sort: 8,
    diagnostic: "A <b>mammal</b>: breathes with alveolar <b>lungs</b>, has a <b>four-chambered heart</b>, uses <b>internal fertilization</b>, and is <b>endothermic</b> — the largest animal in Algonquin.",
    traits: ["Vertebrate <b>mammal</b>", "<b>Lungs</b> with <b>alveoli</b>; <b>four-chambered heart</b>", "<b>Internal fertilization</b>; live birth", "<b>Endothermic</b>; browsing herbivore"] },

  // Fungi
  { id: "trametes", common: "Turkey Tail", binomial: "Trametes versicolor", kingdom: "fungi", grp: "Kingdom Fungi · Basidiomycota · Polyporales", image: "/organisms/trametes.png", alt: "Photograph of Turkey Tail (Trametes versicolor) brackets on wood", caption: "The Sophisticated Caveman. (n.d.). Turkey tail mushrooms [Photograph]. https://www.thesophisticatedcaveman.com/turkey-tail-mushrooms/", sort: 9,
    diagnostic: "A <b>multicellular</b> fungus (<b>chitin</b> walls) growing as a thin, banded <b>bracket</b> on dead wood; a <b>saprotroph</b> releasing <b>spores</b> from <b>pores</b>.",
    traits: ["<b>Multicellular</b> fungus (<b>chitin</b> walls)", "<b>Saprotroph</b> / wood-decomposer", "Banded, fan-shaped bracket", "<b>Spores</b> from pores (a <b>polypore</b>)"] },
  { id: "inonotus", common: "Chaga", binomial: "Inonotus obliquus", kingdom: "fungi", grp: "Kingdom Fungi · Basidiomycota · Hymenochaetales", image: "/organisms/inonotus.png", alt: "Photograph of a Chaga (Inonotus obliquus) conk on a birch trunk", caption: "Swallowtail. (n.d.). Chaga [Photograph]. https://swallowtail.ca/how-to-make-chaga-tea/", sort: 10,
    diagnostic: "A fungus forming a hard, black, charcoal-like <b>sterile conk</b> on living birch; a parasite/<b>saprotroph</b> with <b>chitin</b> walls.",
    traits: ["<b>Multicellular</b> fungus (<b>chitin</b> walls)", "Black, cracked <b>conk</b> on birch", "Parasite that later decays wood", "Reproduces by <b>spores</b>"] },
  { id: "amanita", common: "Fly Agaric", binomial: "Amanita muscaria", kingdom: "fungi", grp: "Kingdom Fungi · Basidiomycota · Agaricales", image: "/organisms/amanita.png", alt: "Photograph of Fly Agaric (Amanita muscaria) with a red, white-warted cap", caption: "Encyclopaedia Britannica. (n.d.). Fly agaric [Photograph]. https://www.britannica.com/science/fly-agaric", sort: 11,
    diagnostic: "A classic <b>cap-and-stalk</b> mushroom with a red <b>cap</b>, white <b>warts</b>, white <b>gills</b>, and a basal <b>volva</b>; a <b>mycorrhizal</b> fungus.",
    traits: ["<b>Multicellular</b> fungus (<b>chitin</b> walls)", "Red cap with white <b>warts</b>; white <b>gills</b>", "Forms <b>mycorrhizae</b> with tree roots", "Toxic (muscimol / ibotenic acid)"] },
  { id: "cantharellus", common: "Chanterelle", binomial: "Cantharellus cibarius", kingdom: "fungi", grp: "Kingdom Fungi · Basidiomycota · Cantharellales", image: "/organisms/cantharellus.png", alt: "Photograph of Chanterelle (Cantharellus cibarius) mushrooms", caption: "Zombie Myco. (n.d.). Chanterelle mushrooms [Photograph]. https://zombiemyco.com/blogs/mushrooms/chanterelle-mushrooms-are-they-safe-to-forage", sort: 12,
    diagnostic: "A yellow, <b>funnel-shaped</b> mushroom with blunt, forking <b>false gills</b> (ridges); a <b>mycorrhizal</b> partner of forest trees.",
    traits: ["<b>Multicellular</b> fungus (<b>chitin</b> walls)", "Yellow, funnel/trumpet shape", "Blunt ridges (<b>false gills</b>)", "<b>Mycorrhizal</b> with trees"] },

  // Prokaryotes & Protists
  { id: "nitrosomonas", common: "Nitrifying Bacterium", binomial: "Nitrosomonas europaea", kingdom: "micro", grp: "Domain Bacteria · Pseudomonadota (Proteobacteria)", image: "/organisms/nitrosomonas.png", alt: "Micrograph of rod-shaped Nitrifying Bacteria (Nitrosomonas europaea)", caption: "Aquatic Creations Group. (n.d.). Nitrifying bacteria [Photograph]. https://aquaticcreationsgroup.com/nitrogen-cycle-overview/", sort: 13,
    diagnostic: "<b>Prokaryotic</b> cell with a <b>peptidoglycan</b> wall; a <b>chemoautotroph</b> that oxidizes ammonia to nitrite, driving the soil <b>nitrogen cycle</b>.",
    traits: ["<b>Prokaryotic</b> — no membrane-bound nucleus", "Cell wall contains <b>peptidoglycan</b>", "<b>Chemoautotroph</b> (energy from ammonia)", "Reproduces by <b>binary fission</b>"] },
  { id: "methanobrevibacter", common: "Methanogen", binomial: "Methanobrevibacter smithii", kingdom: "micro", grp: "Domain Archaea · Euryarchaeota", image: "/organisms/methanobrevibacter.png", alt: "Micrograph of Methanogen (Methanobrevibacter smithii) cells", caption: "Study.com. (n.d.). Methanogens [Photograph]. https://study.com/academy/lesson/methanogens-definition-classification-examples.html", sort: 14,
    diagnostic: "A <b>prokaryotic</b> archaeon whose wall lacks <b>peptidoglycan</b>; an anaerobic <b>methanogen</b> that releases methane in the guts of herbivores such as moose.",
    traits: ["<b>Prokaryotic</b> archaeon", "Cell wall <b>lacks peptidoglycan</b>", "Strict <b>anaerobe</b>", "Produces <b>methane</b> (CH₄) as waste"] },
  { id: "euglena", common: "Euglena", binomial: "Euglena viridis", kingdom: "micro", grp: "Domain Eukarya · Kingdom Protista · Euglenozoa", image: "/organisms/euglena.png", alt: "Micrograph of Euglena (Euglena viridis) cells with green chloroplasts", caption: "Wikipedia. (n.d.). Euglena [Photograph]. https://en.wikipedia.org/wiki/Euglena", sort: 15,
    diagnostic: "A <b>unicellular</b> eukaryote that is <b>photosynthetic</b> (green <b>chloroplasts</b>); swims with a <b>flagellum</b> and detects light with a red <b>eyespot</b>.",
    traits: ["<b>Unicellular</b> eukaryote (protist)", "<b>Photosynthetic</b> — has <b>chloroplasts</b>", "Moves with a <b>flagellum</b>", "Light-sensing <b>eyespot</b>"] },
  { id: "amoeba", common: "Amoeba", binomial: "Amoeba proteus", kingdom: "micro", grp: "Domain Eukarya · Kingdom Protista · Amoebozoa", image: "/organisms/amoeba.png", alt: "Micrograph of an Amoeba (Amoeba proteus) with pseudopodia", caption: "Wikipedia. (n.d.). Amoeba (genus) [Photograph]. https://en.wikipedia.org/wiki/Amoeba_(genus)", sort: 16,
    diagnostic: "A <b>unicellular</b>, non-photosynthetic eukaryote; a <b>heterotroph</b> that moves and engulfs prey with <b>pseudopodia</b> by <b>phagocytosis</b>.",
    traits: ["<b>Unicellular</b> eukaryote (protist)", "<b>Heterotroph</b> — engulfs food (<b>phagocytosis</b>)", "Moves using <b>pseudopodia</b>", "No fixed body shape"] },
  { id: "physarum", common: "Slime Mould", binomial: "Physarum polycephalum", kingdom: "micro", grp: "Domain Eukarya · Kingdom Protista · Myxogastria", image: "/organisms/physarum.png", alt: "Photograph of yellow Slime Mould (Physarum polycephalum) on grass", caption: "Australian Environmental Education. (n.d.). Slime moulds [Photograph]. https://www.australianenvironmentaleducation.com.au/education-resources/slime-moulds-natures-mysterious-decomposers/", sort: 17,
    diagnostic: "A <b>saprotrophic</b> protist (not a true fungus) that creeps across the forest floor as a bright, multinucleate <b>plasmodium</b> feeding on decay.",
    traits: ["Eukaryotic protist (<b>not</b> a true fungus)", "<b>Saprotroph</b> on decaying matter", "Forms a creeping <b>plasmodium</b>", "Reproduces by <b>spores</b>"] },
];

/* --- Key tree (17 couplets). a_target / b_target are node ids or organism ids. --- */
export const seedNodes: KeyNode[] = [
  { id: "q1", num: "1", region: "root", sort: 0, short: "Eukaryotic cells?",
    question: "Are the organism's cells <b>eukaryotic</b> — do they contain a true, membrane-bound <b>nucleus</b> and organelles?",
    a_short: "Yes — eukaryotic", a_label: "Yes — cells are <b>eukaryotic</b> (true nucleus present)", a_target: "q3",
    b_short: "No — prokaryotic", b_label: "No — cells are <b>prokaryotic</b> (DNA free in the <b>cytoplasm</b>)", b_target: "q2" },
  { id: "q2", num: "2", region: "micro", sort: 1, short: "Peptidoglycan wall?",
    question: "Does the cell wall contain <b>peptidoglycan</b>, and does the cell gain energy by <b>chemosynthesis</b> (oxidizing ammonia)?",
    a_short: "Yes — peptidoglycan", a_label: "Yes — <b>peptidoglycan</b> wall; a <b>chemoautotroph</b> of the nitrogen cycle", a_target: "nitrosomonas",
    b_short: "No — a methanogen", b_label: "No <b>peptidoglycan</b>; an anaerobic <b>methanogen</b> that produces methane", b_target: "methanobrevibacter" },
  { id: "q3", num: "3", region: "root", sort: 2, short: "Unicellular?",
    question: "Is the organism <b>unicellular</b> (a single cell) rather than <b>multicellular</b>?",
    a_short: "Yes — unicellular", a_label: "Yes — <b>unicellular</b>", a_target: "q4",
    b_short: "No — multicellular", b_label: "No — <b>multicellular</b> (many specialized cells)", b_target: "q6" },
  { id: "q4", num: "4", region: "micro", sort: 3, short: "Photosynthetic?",
    question: "Is the single cell <b>photosynthetic</b> — does it contain <b>chloroplasts</b> and make its own food (an <b>autotroph</b>)?",
    a_short: "Yes — autotroph", a_label: "Yes — <b>photosynthetic</b>; swims with a <b>flagellum</b>, has a red <b>eyespot</b>", a_target: "euglena",
    b_short: "No — heterotroph", b_label: "No — a <b>heterotroph</b>", b_target: "q5" },
  { id: "q5", num: "5", region: "micro", sort: 4, short: "Feeds by pseudopodia?",
    question: "Does the cell feed by engulfing prey with <b>pseudopodia</b> (a <b>heterotroph</b>), rather than absorbing decay?",
    a_short: "Yes — pseudopodia", a_label: "Yes — ingestive <b>heterotroph</b> moving by <b>pseudopodia</b> (<b>phagocytosis</b>)", a_target: "amoeba",
    b_short: "No — saprotroph", b_label: "No — a <b>saprotroph</b> that creeps as a multinucleate <b>plasmodium</b>", b_target: "physarum" },
  { id: "q6", num: "6", region: "fungi", sort: 5, short: "Saprotroph fungus?",
    question: "Is the organism a <b>saprotroph</b> with cell walls of <b>chitin</b> that feeds by <b>absorption</b> (a fungus)?",
    a_short: "Yes — a fungus", a_label: "Yes — a <b>fungus</b> (<b>chitin</b> walls, <b>absorptive</b> feeding, <b>spores</b>)", a_target: "q7",
    b_short: "No — plant/animal", b_label: "No — a <b>plant</b> or an <b>animal</b>", b_target: "q9" },
  { id: "q7", num: "7", region: "fungi", sort: 6, short: "Bracket on wood?",
    question: "Does the fungus grow as a tough <b>bracket</b> (shelf) on wood, rather than a fleshy <b>cap-and-stalk</b> mushroom?",
    a_short: "Yes — a bracket", a_label: "Yes — a woody/leathery <b>bracket fungus</b>", a_target: "q8",
    b_short: "No — capped/funnel", b_label: "No — a fleshy <b>cap</b> or <b>funnel</b> mushroom", b_target: "q8b" },
  { id: "q8", num: "8", region: "fungi", sort: 7, short: "Thin, banded, multi-coloured?",
    question: "Is the bracket thin and banded with concentric, multi-coloured zones (like a fanned tail), with <b>pores</b> beneath?",
    a_short: "Yes — banded", a_label: "Yes — thin, banded, fan-shaped bracket with <b>pores</b> (a <b>polypore</b>)", a_target: "trametes",
    b_short: "No — black birch mass", b_label: "No — a hard, black, charcoal-like <b>sterile conk</b> on birch", b_target: "inonotus" },
  { id: "q8b", num: "8b", region: "fungi", sort: 8, short: "Red cap, white spots?",
    question: "Does the mushroom have a bright red <b>cap</b> dotted with white <b>warts</b>, with true <b>gills</b> beneath?",
    a_short: "Yes — red, warty cap", a_label: "Yes — red cap, white <b>warts</b>, white <b>gills</b>, basal <b>volva</b>", a_target: "amanita",
    b_short: "No — funnel-shaped", b_label: "No — yellow, <b>funnel-shaped</b> body with blunt <b>false gills</b>", b_target: "cantharellus" },
  { id: "q9", num: "9", region: "split", sort: 9, short: "Photosynthetic plant?",
    question: "Is the organism a <b>photosynthetic</b> <b>plant</b> (makes food in <b>chloroplasts</b>; cell walls of <b>cellulose</b>)?",
    a_short: "Yes — a plant", a_label: "Yes — a <b>plant</b> (<b>autotroph</b>)", a_target: "q10",
    b_short: "No — an animal", b_label: "No — an <b>animal</b> (ingestive <b>heterotroph</b>)", b_target: "q14" },
  { id: "q10", num: "10", region: "plant", sort: 10, short: "Vascular tissue?",
    question: "Does the plant have <b>vascular tissue</b> — <b>xylem</b> and <b>phloem</b> — to transport water and food?",
    a_short: "Yes — vascular", a_label: "Yes — a <b>vascular</b> plant", a_target: "q11",
    b_short: "No — non-vascular", b_label: "No — a <b>non-vascular</b> plant that absorbs water directly; reproduces by <b>spores</b>", b_target: "sphagnum" },
  { id: "q11", num: "11", region: "plant", sort: 11, short: "Reproduces by seeds?",
    question: "Does the vascular plant reproduce by <b>seeds</b> rather than by <b>spores</b>?",
    a_short: "Yes — seeds", a_label: "Yes — a <b>seed plant</b>", a_target: "q12",
    b_short: "No — spores", b_label: "No — a <b>seedless vascular</b> plant (<b>pteridophyte</b>) with <b>spores</b> in <b>sori</b>", b_target: "matteuccia" },
  { id: "q12", num: "12", region: "plant", sort: 12, short: "Seeds enclosed in fruit?",
    question: "Are the <b>seeds</b> enclosed in a <b>fruit / ovary</b> (an <b>angiosperm</b>), rather than exposed on <b>cones</b>?",
    a_short: "Yes — enclosed", a_label: "Yes — a <b>flowering plant</b> (<b>angiosperm</b>); seeds enclosed in a <b>fruit</b>", a_target: "q13",
    b_short: "No — cones", b_label: "No — a <b>gymnosperm</b>; naked seeds on woody <b>cones</b>, needle leaves", b_target: "pinus" },
  { id: "q13", num: "13", region: "plant", sort: 13, short: "Parallel leaf veins?",
    question: "Does the flowering plant have <b>parallel leaf veins</b> and flower parts in threes (a <b>monocot</b>)?",
    a_short: "Yes — monocot", a_label: "Yes — a <b>monocot</b>: <b>parallel venation</b>, three-part flower", a_target: "trillium",
    b_short: "No — dicot", b_label: "No — a <b>dicot</b>: broad leaves with <b>net-like (reticulate) venation</b>", b_target: "acer" },
  { id: "q14", num: "14", region: "animal", sort: 14, short: "Tracheae + open circulation?",
    question: "Does the animal breathe through <b>spiracles</b> and <b>tracheae</b> with an <b>open circulatory system</b> (an <b>arthropod / insect</b>)?",
    a_short: "Yes — an insect", a_label: "Yes — an <b>insect</b>: <b>tracheal</b> breathing, <b>open circulation</b>, jointed legs", a_target: "monochamus",
    b_short: "No — a vertebrate", b_label: "No — a <b>vertebrate</b>", b_target: "q15" },
  { id: "q15", num: "15", region: "animal", sort: 15, short: "Gills, 2-chambered heart?",
    question: "Does the vertebrate breathe with <b>gills</b> and have a <b>two-chambered heart</b> with single-loop circulation (a fish)?",
    a_short: "Yes — a fish", a_label: "Yes — a <b>fish</b>: <b>gills</b>, <b>two-chambered heart</b>, <b>external fertilization</b>", a_target: "salvelinus",
    b_short: "No — a tetrapod", b_label: "No — a <b>tetrapod</b>", b_target: "q16" },
  { id: "q16", num: "16", region: "animal", sort: 16, short: "Moist skin, 3-chambered heart?",
    question: "Does the animal have moist <b>skin</b> for <b>cutaneous gas exchange</b>, a <b>three-chambered heart</b>, and <b>external fertilization</b> (an <b>amphibian</b>)?",
    a_short: "Yes — an amphibian", a_label: "Yes — an <b>amphibian</b>: moist skin, <b>three-chambered heart</b>, <b>external fertilization</b>, <b>metamorphosis</b>", a_target: "lithobates",
    b_short: "No — a mammal", b_label: "No — a <b>mammal</b>: <b>lungs</b> with <b>alveoli</b>, <b>four-chambered heart</b>, <b>internal fertilization</b>, <b>endothermic</b>", b_target: "alces" },
];

export const seedConcepts: { heading: string; body: string; sort: number }[] = [
  { sort: 0, heading: "Taxonomy & Classification",
    body: "Every organism in this key is placed using <b>taxonomy</b> — the science of naming and classifying life (Di Giuseppe et al., 2011). Biologists sort life into a nested <b>hierarchy</b>: <b>Domain → Kingdom → Phylum → Class → Order → Family → Genus → Species</b>, and each species carries a two-word <b>binomial name</b> with a capitalized <b>genus</b> and a lowercase species epithet, such as <i>Acer saccharum</i>. The first branch of this key divides <b>prokaryotes</b> — <b>bacteria</b> like <i>Nitrosomonas europaea</i> and <b>archaea</b> like <i>Methanobrevibacter smithii</i>, whose cells have no membrane-bound <b>nucleus</b> — from <b>eukaryotes</b>, which include protists, fungi, plants, and animals. Organisms are then separated by whether they are <b>unicellular</b> (a single <i>Euglena</i> or <i>Amoeba</i> cell) or <b>multicellular</b> (a Sugar Maple or a Moose), and by their <b>morphology</b> (body form) and <b>habitat</b> within Algonquin's forests, lakes, and wetlands (Ontario Parks, 2023). A final clue is <b>feeding strategy</b>: <b>autotrophs</b> such as plants and <i>Euglena</i> make their own food, <b>heterotrophs</b> such as the moose and <i>Amoeba</i> ingest other organisms, and <b>saprotrophs</b> such as <i>Trametes versicolor</i> absorb nutrients from dead matter." },
  { sort: 1, heading: "Gas Exchange in Plants",
    body: "Plants take in the carbon dioxide needed for <b>photosynthesis</b> and release oxygen entirely by <b>diffusion</b>, with no breathing movements (Raven et al., 2020). Whether a plant is <b>vascular</b> or <b>non-vascular</b> shapes how it exchanges gas: the <b>non-vascular</b> moss <i>Sphagnum capillifolium</i> is only a few cells thick, so gases diffuse directly across its surface, while a large <b>vascular</b> plant needs dedicated pores. In leaves, gas exchange happens through tiny adjustable pores called <b>stomata</b> (woody stems use <b>lenticels</b>). Inside a broad-leaf <b>dicot</b> such as <i>Acer saccharum</i>, incoming light is captured by the tightly packed, column-shaped cells of the <b>palisade mesophyll</b> just beneath the upper surface, while the loosely packed cells and air spaces of the <b>spongy mesophyll</b> below let carbon dioxide and oxygen <b>diffuse</b> freely to and from the <b>stomata</b>. A <b>monocot</b> such as <i>Trillium grandiflorum</i> also breathes through <b>stomata</b>, but its leaf shows <b>parallel venation</b> and a less sharply layered mesophyll than the dicot's, showing how leaf structure varies across flowering plants (Di Giuseppe et al., 2011)." },
  { sort: 2, heading: "Transport in Plants",
    body: "Because <b>diffusion</b> alone cannot move materials over long distances, large <b>vascular plants</b> depend on transport tissues. Water first enters the roots by <b>osmosis</b> — the movement of water across a <b>semipermeable</b> membrane from a region of high <b>water potential</b> to one of low water potential (Raven et al., 2020). From the roots, <b>xylem</b> carries water and dissolved minerals upward, pulled by the <b>cohesion–tension</b> generated as water evaporates from the leaves during <b>transpiration</b>, while <b>phloem</b> transports the sugars made in photosynthesis from <b>source</b> to <b>sink</b> in a process called <b>translocation</b>. This two-way vascular transport operates in both <b>monocots</b> such as <i>Trillium grandiflorum</i> and <b>dicots</b> such as <i>Acer saccharum</i>, which differ mainly in how their <b>vascular bundles</b> are arranged. The <b>non-vascular</b> moss <i>Sphagnum capillifolium</i> has no <b>xylem</b> or <b>phloem</b>, so it stays small and moves water and dissolved substances by <b>diffusion</b> and <b>osmosis</b> directly, cell to cell (Di Giuseppe et al., 2011)." },
  { sort: 3, heading: "Gas Exchange in Animals",
    body: "In animals, <b>gas exchange</b> also occurs by <b>diffusion</b>, and it must always take place across a thin, moist, <b>semipermeable</b> surface where oxygen can dissolve (Raven et al., 2020). Different Algonquin animals solve this in different ways. The <b>insect</b> White-spotted Sawyer Beetle (<i>Monochamus scutellatus</i>) pipes air directly to its tissues through branching tubes called <b>tracheae</b> that open at surface pores called <b>spiracles</b>. The <b>fish</b> Brook Trout (<i>Salvelinus fontinalis</i>) passes water over feathery <b>gills</b>, using <b>countercurrent exchange</b> to pull dissolved oxygen from the water. The <b>amphibian</b> Wood Frog (<i>Lithobates sylvaticus</i>) exchanges much of its gas by <b>diffusion</b> straight across its moist, <b>semipermeable</b> <b>skin</b> — a process called <b>cutaneous</b> gas exchange. The <b>mammal</b> Moose (<i>Alces alces</i>) draws air into <b>lungs</b> by <b>ventilation</b> — the active breathing movements that continually refresh the air — so oxygen can <b>diffuse</b> across the vast surface of the <b>alveoli</b>, which are wrapped in tiny blood <b>capillaries</b> (Di Giuseppe et al., 2011)." },
  { sort: 4, heading: "Transport in Animals",
    body: "Once gases and nutrients enter an animal, a <b>circulatory system</b> distributes them, and these systems grow more complex across the animal kingdom (Di Giuseppe et al., 2011). The <b>insect</b> sawyer beetle has an <b>open circulatory system</b>: a simple tubular heart pumps <b>hemolymph</b> into open body cavities where it bathes the organs directly before draining back. <b>Vertebrates</b> instead use a <b>closed circulatory system</b>, in which blood stays inside vessels. The Brook Trout has a <b>single closed</b> circulatory system built around a <b>two-chambered heart</b>, so blood passes through the heart just once per full circuit of the body. Mammals such as the Moose have a <b>double closed</b> circulatory system with a <b>four-chambered heart</b> that completely separates oxygen-rich from oxygen-poor blood and pumps it through the heart twice per circuit. The Wood Frog is an evolutionary intermediate: its <b>three-chambered heart</b> only partially separates the two blood streams, matching an amphibian's mixed aquatic and terrestrial life (Raven et al., 2020)." },
  { sort: 5, heading: "Reproductive Strategies",
    body: "The organisms of Algonquin reproduce in strikingly varied ways that span both <b>asexual reproduction</b> and <b>sexual reproduction</b> (Government of Canada, 2023). Many microbes reproduce <b>asexually</b> by <b>binary fission</b>, in which one cell copies its DNA and splits into two identical cells — the strategy of the <b>bacterium</b> <i>Nitrosomonas europaea</i>, the <b>archaeon</b> <i>Methanobrevibacter smithii</i>, and the protist <i>Amoeba proteus</i>. <b>Fungi</b> can also reproduce asexually by <b>fragmentation</b>, where a broken piece of <b>mycelium</b> grows into a new individual, and by <b>budding</b>, in which a small outgrowth pinches off (as in yeasts). Countless species disperse using microscopic <b>spores</b> — the <b>moss</b> <i>Sphagnum</i>, the <b>fern</b> <i>Matteuccia struthiopteris</i> (which bears its spores in <b>sori</b>), and fungi such as <i>Amanita muscaria</i>. Many plants also spread without seeds through <b>vegetative propagation</b>, growing clones from runners, rhizomes, or fragments. In <b>sexual reproduction</b>, the Brook Trout and Wood Frog rely on <b>external fertilization</b>, releasing eggs and sperm into water, whereas the Moose uses <b>internal fertilization</b> and bears live young — a <b>K-selected</b> strategy of few, well-cared-for offspring (Di Giuseppe et al., 2011)." },
];

export const seedReferences: { entry: string; sort: number }[] = [
  { sort: 0, entry: "Di Giuseppe, M., Vavitsas, A., Fraser, D., Ku, D., Lisser, B., &amp; Vucic, S. (2011). <i>Nelson biology 11</i>. Nelson Education." },
  { sort: 1, entry: "Government of Canada. (2023). <i>Species profiles</i>. Canadian Wildlife Service. https://www.canada.ca" },
  { sort: 2, entry: "Government of Ontario. (n.d.). <i>Ontario's forest regions: Great Lakes–St. Lawrence forest</i>. Ministry of Natural Resources and Forestry. https://www.ontario.ca" },
  { sort: 3, entry: "Ontario Parks. (2023). <i>Algonquin Provincial Park</i>. Ontario Parks. https://www.ontarioparks.com/park/algonquin" },
  { sort: 4, entry: "Raven, P. H., Johnson, G. B., Mason, K. A., Losos, J. B., &amp; Duncan, T. (2020). <i>Biology</i> (12th ed.). McGraw-Hill Education." },
];

export const seedMeta: SiteMetaData = {
  siteTitle: "A Dichotomous Key to 18 Organisms of Algonquin Provincial Park",
  subtitle: "Great Lakes–St. Lawrence Forest Region · SBI3U Biology (Ontario)",
  ecozone: "Great Lakes–St. Lawrence Forest Region · Algonquin Provincial Park, Ontario",
  introHeading: "A field key to the living things of Algonquin",
  introBlurb:
    "This is an interactive <b>dichotomous key</b> for the <b>Great Lakes–St. Lawrence Forest Region</b> (Government of Ontario, n.d.), drawn from the mixed forests, lakes, and wetlands of <b>Algonquin Provincial Park</b>, Ontario (Ontario Parks, 2023). A <b>dichotomous key</b> identifies organisms through a series of paired, either/or questions: at each branch you pick the description that fits, following the tree until you reach a single organism. This key covers <b>18 organisms</b> spanning every <b>kingdom</b> of life, applying the <b>taxonomy</b>, <b>gas exchange</b>, <b>transport</b>, and <b>reproduction</b> concepts studied in SBI3U (Di Giuseppe et al., 2011).",
  howToHeading: "How to use the tree",
  howTo: [
    "Start at the root node, <b>Couplet 1</b>, on the left of the tree.",
    "Read each <b>question</b> and click the choice — <b>a</b> or <b>b</b> — that matches your organism. Bolded words are the diagnostic <b>key terms</b>.",
    "The chosen branch <b>lights up in copper</b> and the breadcrumb records your path until you reach a <b>species endpoint</b>.",
    "<b>Hover</b> or <b>focus</b> any node to enlarge it and read the full detail. On a phone, use the step-through version below the tree.",
  ],
  referencesNote:
    "References are listed alphabetically in <b>APA style</b>. <b>In-text citations</b> (author, year) appear throughout the intro and Biology Concepts sections. <i>Replace or verify these with the exact sources you used for your assignment.</i>",
  footer:
    "Interactive dichotomous key · <b>SBI3U Biology</b> · Great Lakes–St. Lawrence Forest Region, Algonquin Provincial Park.",
};
